### ISSUE TITLE
Change scripted link

### ISSUE THREAD

**Issue by dwijnand** [sbt/sbt-autoplugin.g8#1]
Link to http://www.scala-sbt.org/0.13/docs/Testing-sbt-plugins.html instead.

**Comment by jastice** [comment]
done :)

**Comment by dwijnand** [comment]
Not in https://github.com/jastice/sbt-autoplugin.g8/blob/master/src/main/g8/README.md, which is the user-facing one.

**Comment by jastice** [comment]
fixed
