### ISSUE TITLE
Template doesn't work on windows because of filenames with "

### ISSUE THREAD

**Issue by wwbakker** [sbt/sbt-autoplugin.g8#4]
When I run the sbt new command for this g8 plugin, the command fails with the following error:

```
[error] org.eclipse.jgit.dircache.InvalidPathException: Invalid path: src/main/g8/src/main/scala/$package$/$name;format=
"Camel"$Plugin.scala
```
I wanted to investigate this, and maybe do a pull request, however when I tried to clone the whole respository I basically got the same error:
```
PS C:\repos> git clone git@github.com:wwbakker/sbt-autoplugin.g8.git
Cloning into 'sbt-autoplugin.g8'...
remote: Counting objects: 182, done.
Receiving objects:  29% (53/182)    0 (delta 0), pack-reused 182R
Receiving objects: 100% (182/182), 16.35 KiB | 1.49 MiB/s, done.
Resolving deltas: 100% (52/52), done.
error: unable to create file src/main/g8/src/main/scala/$package$/$name;format="Camel"$Plugin.scala: Invalid argument
fatal: cannot create directory at 'src/main/g8/src/sbt-test/$name;format="norm"$': Invalid argument
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'
```
Then it occurred to me. I'm running windows, and in NTFS files cannot have the " sign in them, so it cannot create the files.

Since I'm on windows and am unable to even clone the repository I'm unable to fix it myself.

P.S. $ sign is no problem.

**Comment by jastice** [comment]
Thanks for pointing this out. I'll try to get to it later in July probably

**Comment by jastice** [comment]
For reference: https://github.com/foundweekends/giter8/issues/130

**Comment by jastice** [comment]
should work now :)

**Comment by wwbakker** [comment]
Works 👍
